import type { CSSProperties } from "react";

export const BASIC_PANE_WIDTH = 300;
export const SIDEBAR_PANE_WIDTH = 360;
export const styles: Record<string, CSSProperties> = {
  /* Page shell */
  page: {
    width: "100%",
    height: "100vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    maxWidth: 1600,
    margin: "0 auto",
    padding: "0 28px 28px",
    background: "var(--bg)",
  },
  heading: {
    display: "grid",
    gap: 8,
    position: "sticky",
    top: 0,
    zIndex: 15,
    paddingTop: 20,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottom: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 92%, var(--bg))",
  },
  headingRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  pageTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 700,
    color: "var(--ink)",
    lineHeight: 1.2,
  },
  notice: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 24,
    padding: "0 8px",
    border: "none",
    background: "color-mix(in srgb, white 72%, var(--accent-soft))",
    color: "var(--ink-2)",
    fontSize: 12,
    lineHeight: 1,
    display: "inline-flex",
    alignItems: "center",
  },
  workspaceShell: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    gap: 14,
  },
  workspaceShellCompact: {
    flexDirection: "column",
    overflowY: "auto",
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  mainColumnCompact: {
    overflow: "visible",
  },
  editorArea: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    gap: 14,
  },
  editorAreaCompact: {
    flexDirection: "column",
    overflow: "visible",
  },
  basicPane: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    minWidth: 0,
    border: "none",
    background: "transparent",
  },
  slotsPane: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    border: "1px solid var(--border)",
    background: "var(--panel)",
  },
  compactPane: {
    overflow: "visible",
  },
  basicPaneHead: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    minHeight: 24,
    padding: "0 4px 10px 0",
  },
  basicPaneTitle: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "var(--muted)",
  },
  basicPaneActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  rewritePopoverWrap: {
    position: "static",
    display: "inline-flex",
  },
  basicIconButton: {
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    width: 32,
    height: 32,
    padding: 0,
    background: "color-mix(in srgb, white 72%, var(--surface))",
    color: "var(--ink)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  basicIconButtonPrimary: {
    border: "none",
    background: "var(--accent)",
    color: "white",
  },
  basicIconButtonDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  rewritePopover: {
    position: "absolute",
    top: "calc(100% + 8px)",
    left: 0,
    zIndex: 20,
    width: 220,
    display: "grid",
    gap: 10,
    padding: "12px 12px 10px",
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "var(--panel)",
    boxShadow: "0 12px 28px rgba(13, 32, 40, 0.12)",
  },
  rewritePopoverSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  rewritePopoverValue: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--ink)",
  },
  rewritePopoverHint: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--muted)",
  },
  rewritePopoverButton: {
    border: "none",
    minHeight: 32,
    padding: "0 12px",
    background: "var(--accent)",
    color: "white",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  basicPaneCard: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    paddingTop: 12,
    background: "transparent",
    flex: 1,
    minHeight: 0,
  },
  basicPaneSection: {
    display: "grid",
    gap: 12,
  },
  basicPanePrimarySection: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    flex: 1,
    minHeight: 0,
  },
  basicPaneSectionSeparated: {
    paddingTop: 14,
    marginTop: 14,
    borderTop: "1px solid color-mix(in srgb, var(--border) 68%, white)",
  },
  panelHeader: {
    flexShrink: 0,
    padding: "10px 16px",
    borderBottom: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 40,
    gap: 8,
  },
  panelHeaderActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  panelBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "16px 18px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  slotDropArea: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
  },

  /* Left: editor */
  editorPanel: {
    border: "1px solid var(--border)",
    background: "var(--panel)",
    padding: 20,
    display: "grid",
    gap: 14,
    alignContent: "start",
  },
  sidebarPane: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
  },
  sidebarPaneCompact: {
    overflow: "visible",
  },
  resizer: {
    width: 4,
    flexShrink: 0,
    alignSelf: "stretch",
    background: "var(--border)",
    cursor: "col-resize",
  },
  resizerHidden: {
    display: "none",
  },
  sidebarSection: {
    border: "1px solid var(--border)",
    background: "color-mix(in srgb, white 99%, var(--panel))",
    overflow: "hidden",
    flexShrink: 0,
  },
  sidebarSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    border: "none",
    background: "transparent",
    padding: "10px 12px",
    cursor: "pointer",
    textAlign: "left",
  },
  sidebarSectionBody: {
    padding: "0 12px 12px",
    display: "grid",
    gap: 8,
    alignContent: "start",
  },
  sidebarListSection: {
    flex: 1,
    overflowY: "auto",
    minHeight: 0,
    alignContent: "start",
  },
  sidebarToggleIcon: {
    color: "var(--muted)",
    display: "inline-flex",
    alignItems: "center",
  },

  /* Panel header */
  panelHead: {
    paddingBottom: 10,
    borderBottom: "1px solid color-mix(in srgb, var(--border) 68%, white)",
    marginBottom: 0,
  },
  sidebarHint: {
    margin: 0,
    fontSize: 12,
    color: "var(--muted)",
    lineHeight: 1.6,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: "var(--ink)",
    lineHeight: 1.4,
  },
  checkboxLabel: {
    color: "var(--muted)",
  },
  panelTitle: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "var(--muted)",
  },

  /* Form elements */
  fieldGroup: {
    display: "grid",
    gap: 4,
  },
  collapsibleFieldToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  },
  summaryFieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    flex: 1,
    minHeight: 0,
  },
  fieldHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  fieldHint: {
    fontSize: 11,
    color: "var(--muted)",
    letterSpacing: "0.03em",
  },
  slotDropZoneActive: {
    boxShadow: "0 0 0 2px var(--accent-soft) inset",
    borderRadius: 4,
    padding: 8,
    background: "color-mix(in srgb, white 70%, var(--accent-soft))",
  },
  slotPaneContent: {
    width: "100%",
    maxWidth: 760,
    margin: "0 auto",
    minWidth: 0,
    display: "grid",
    gap: 0,
  },
  slotList: {
    display: "grid",
    gap: 0,
  },
  slotInsertMarker: {
    height: 10,
    borderRadius: 999,
    transition: "background 140ms ease, transform 140ms ease, box-shadow 140ms ease",
  },
  slotInsertMarkerActive: {
    background: "var(--accent)",
    boxShadow: "0 0 0 3px var(--accent-soft)",
    transform: "scaleY(1.2)",
  },
  modeSwitch: {
    display: "inline-flex",
    border: "1px solid var(--border)",
    background: "color-mix(in srgb, white 88%, var(--panel))",
    minHeight: 28,
    minWidth: 0,
    flex: 1,
  },
  modeSwitchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "space-between",
    flexWrap: "nowrap",
  },
  modeSwitchButton: {
    border: "none",
    background: "transparent",
    color: "var(--muted)",
    padding: "0 10px",
    fontSize: 12,
    cursor: "pointer",
    minHeight: 28,
    flex: 1,
  },
  modeSwitchButtonActive: {
    border: "none",
    background: "color-mix(in srgb, white 65%, var(--accent-soft))",
    color: "var(--ink)",
    fontWeight: 600,
    padding: "0 10px",
    fontSize: 12,
    cursor: "pointer",
    minHeight: 28,
    flex: 1,
  },
  emptySlotDropTarget: {
    border: "1px dashed var(--border)",
    background: "var(--panel)",
    color: "var(--muted)",
    padding: "14px 12px",
    fontSize: 12,
    lineHeight: 1.6,
    textAlign: "center",
  },
  emptySlotDropTargetActive: {
    border: "1px dashed var(--accent)",
    background: "color-mix(in srgb, white 70%, var(--accent-soft))",
    color: "var(--ink)",
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--muted)",
  },
  input: {
    width: "100%",
    height: 38,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "0 10px",
    color: "var(--ink)",
    fontSize: 14,
  },
  select: {
    width: "100%",
    height: 38,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "0 10px",
    color: "var(--ink)",
    fontSize: 14,
  },
  selectCompact: {
    width: 88,
    height: 38,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "0 8px",
    color: "var(--ink)",
    fontSize: 14,
  },
  textarea: {
    width: "100%",
    minHeight: 96,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "10px 12px",
    resize: "vertical",
    color: "var(--ink)",
    fontSize: 14,
    lineHeight: 1.65,
  },
  summaryTextarea: {
    width: "100%",
    minHeight: 0,
    flex: 1,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "10px 12px",
    resize: "vertical",
    color: "var(--ink)",
    fontSize: 14,
    lineHeight: 1.65,
  },
  textareaLg: {
    width: "100%",
    minHeight: 120,
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    padding: "10px 12px",
    resize: "vertical",
    color: "var(--ink)",
    fontSize: 14,
    lineHeight: 1.65,
  },
  fileInput: {
    width: "100%",
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    padding: "8px 10px",
    background: "color-mix(in srgb, white 72%, var(--surface))",
    color: "var(--ink)",
    fontSize: 14,
  },
  promptSuggestionCard: {
    border: "none",
    borderLeft: "2px solid color-mix(in srgb, var(--accent) 52%, var(--border))",
    background: "transparent",
    padding: "4px 0 4px 10px",
    display: "grid",
    gap: 6,
  },
  promptSuggestionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  promptSuggestionSource: {
    fontSize: 12,
    color: "var(--muted)",
  },
  promptSuggestionNote: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--muted)",
  },
  promptSuggestionBody: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.65,
    color: "var(--ink)",
    whiteSpace: "pre-wrap",
  },
  runtimePromptPreview: {
    margin: 0,
    minHeight: 96,
    maxHeight: 156,
    border: "1px solid var(--border)",
    background: "var(--bg)",
    padding: "10px 12px",
    color: "var(--ink)",
    fontSize: 12,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    overflowY: "auto",
    overflowX: "auto",
  },
  range: {
    width: "100%",
  },

  /* Slot card */
  slotCard: {
    border: "none",
    borderBottom: "1px solid color-mix(in srgb, var(--border) 68%, white)",
    background: "transparent",
    padding: "6px 0 8px",
    display: "grid",
    gap: 4,
    marginBottom: 0,
    transition: "transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease, opacity 180ms ease",
  },
  slotCardDragging: {
    opacity: 0.7,
    transform: "scale(0.99)",
    borderBottom: "1px solid var(--teal)",
  },
  slotCardMoveUp: {
    transform: "translateY(-8px)",
    borderBottom: "1px solid var(--accent)",
  },
  slotCardMoveDown: {
    transform: "translateY(8px)",
    borderBottom: "1px solid var(--accent)",
  },
  slotHeader: {
    display: "grid",
    gap: 4,
    cursor: "pointer",
    minWidth: 0,
  },
  slotHeaderMain: {
    display: "grid",
    gridTemplateColumns: "18px minmax(110px, 132px) minmax(0, 1fr) auto",
    gap: 6,
    alignItems: "center",
    minWidth: 0,
  },
  slotHeaderActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  dragHandle: {
    color: "var(--muted)",
    cursor: "grab",
    userSelect: "none",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  slotKindSelect: {
    width: "100%",
    minWidth: 0,
    height: 28,
    border: "none",
    borderBottom: "1px solid color-mix(in srgb, var(--border) 68%, white)",
    background: "transparent",
    padding: "0 2px 0 0",
    fontSize: 12,
    color: "var(--ink)",
  },
  slotLabelInput: {
    width: "100%",
    minWidth: 0,
    height: 28,
    border: "none",
    borderBottom: "1px solid color-mix(in srgb, var(--border) 68%, white)",
    background: "transparent",
    padding: "0 2px",
    fontSize: 12,
    color: "var(--ink)",
  },
  removeBtn: {
    flex: "0 0 auto",
    height: 24,
    width: 24,
    border: "none",
    background: "transparent",
    color: "var(--muted)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  slotContent: {
    width: "100%",
    minHeight: 60,
    border: "1px solid color-mix(in srgb, var(--border) 62%, white)",
    background: "color-mix(in srgb, white 55%, var(--bg))",
    padding: "8px 10px",
    resize: "vertical",
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--ink)",
  },
  slotHintText: {
    fontSize: 12,
    color: "var(--muted)",
    lineHeight: 1.6,
  },
  weightRow: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: 6,
    alignItems: "center",
  },
  slotPreview: {
    display: "block",
    maxWidth: "56ch",
    paddingLeft: 24,
    fontSize: 11,
    color: "var(--muted)",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    minWidth: 0,
  },
  slotToggleBtn: {
    border: "none",
    background: "transparent",
    color: "var(--muted)",
    cursor: "pointer",
    padding: 0,
    width: 24,
    height: 24,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },

  /* Compact 2-col grid */
  compactGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
  },

  /* Buttons */
  primaryBtn: {
    border: "1px solid color-mix(in srgb, var(--accent) 38%, var(--border))",
    background: "color-mix(in srgb, white 86%, var(--accent-soft))",
    color: "var(--ink)",
    height: 36,
    padding: "0 14px",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ghostBtn: {
    border: "1px solid var(--border)",
    background: "color-mix(in srgb, white 98%, var(--panel))",
    color: "var(--ink)",
    height: 36,
    padding: "0 12px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtn: {
    border: "none",
    background: "transparent",
    color: "var(--muted)",
    height: 24,
    minWidth: 24,
    padding: 0,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  tagBtn: {
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--ink)",
    height: 28,
    padding: "0 10px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  sidebarActionRow: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
  sidebarCardActions: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  sidebarIconButton: {
    border: "1px solid color-mix(in srgb, var(--border) 76%, white)",
    width: 28,
    height: 28,
    padding: 0,
    background: "color-mix(in srgb, white 72%, var(--surface))",
    color: "var(--ink)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sidebarIconButtonPrimary: {
    border: "none",
    background: "var(--accent)",
    color: "white",
  },
  cardSummaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 10,
  },
  cardSummaryItem: {
    border: "1px solid var(--border)",
    background: "color-mix(in srgb, white 98%, var(--panel))",
    padding: "10px 12px",
    display: "grid",
    gap: 4,
  },
  cardSummaryValue: {
    fontSize: 18,
    fontWeight: 700,
    color: "var(--ink)",
  },
  cardSummaryLabel: {
    fontSize: 11,
    color: "var(--muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  cardList: {
    display: "grid",
    gap: 6,
  },
  personaSlotLibraryCard: {
    border: "1px solid var(--border)",
    background: "transparent",
    padding: 10,
    display: "grid",
    gap: 6,
    cursor: "pointer",
    transition: "transform 160ms ease, box-shadow 160ms ease, opacity 160ms ease, border-color 160ms ease, background 160ms ease",
  },
  personaSlotLibraryCardSelected: {
    border: "1px solid var(--accent)",
    background: "color-mix(in srgb, white 92%, var(--accent-soft))",
  },
  personaSlotLibraryCardDragging: {
    opacity: 0.7,
    transform: "scale(0.99)",
  },
  personaLibraryCard: {
    border: "1px solid var(--border)",
    background: "transparent",
    padding: 10,
    display: "grid",
    gap: 6,
  },
  personaLibraryCardSelected: {
    border: "1px solid var(--accent)",
    background: "color-mix(in srgb, white 94%, var(--accent-soft))",
  },
  libraryCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  libraryCardTitleRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  libraryCardDragHandle: {
    border: "1px solid var(--border)",
    background: "var(--panel)",
    color: "var(--ink)",
    width: 30,
    height: 30,
    cursor: "grab",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  },
  libraryCardTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--ink)",
    minWidth: 0,
  },
  libraryCardBadge: {
    padding: 0,
    fontSize: 11,
    color: "var(--muted)",
  },
  libraryCardMetaRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    fontSize: 11,
    color: "var(--muted)",
  },
  libraryCardContent: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.7,
    color: "var(--ink)",
  },
  libraryCardNote: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--muted)",
  },

  /* Asset info card */
  assetCard: {
    border: "1px solid var(--border)",
    background: "transparent",
    padding: "10px",
    display: "grid",
    gap: 6,
  },
  generatedResultCard: {
    display: "grid",
    gap: 4,
    paddingTop: 8,
    border: "none",
    borderTop: "1px solid color-mix(in srgb, var(--border) 68%, white)",
    background: "transparent",
  },
  generatedResultTitle: {
    fontSize: 13,
    color: "var(--ink)",
  },
  generatedResultSummary: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--muted)",
  },
  generatedResultMeta: {
    margin: 0,
    fontSize: 11,
    lineHeight: 1.4,
    color: "var(--muted)",
  },
  generatedCardPreviewList: {
    margin: 0,
    padding: "4px 0 0 18px",
    display: "grid",
    gap: 6,
    maxHeight: 180,
    overflowY: "auto",
  },
  generatedCardPreviewItem: {
    display: "grid",
    gap: 2,
    fontSize: 11,
    lineHeight: 1.45,
    color: "var(--muted)",
  },
  assetRow: {
    display: "grid",
    gridTemplateColumns: "80px 1fr",
    gap: 8,
    fontSize: 12,
    wordBreak: "break-all",
  },
  assetLabel: { color: "var(--muted)" },

  /* Chat reply */
  chatReply: {
    padding: "10px 12px",
    border: "1px solid var(--border)",
    background: "var(--panel)",
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--ink)",
  },

  /* Text helpers */
  mutedText: { fontSize: 12, color: "var(--muted)" },
  hiddenInput: { display: "none" },

  /* Error states */
  errorBanner: {
    border: "1px solid color-mix(in srgb, var(--negative) 40%, transparent)",
    background: "color-mix(in srgb, var(--negative) 8%, white)",
    color: "var(--negative)",
    padding: "10px 12px",
    marginBottom: 14,
    fontSize: 13,
  },
  errorText: { fontSize: 12, color: "var(--negative)", lineHeight: 1.5, margin: 0 },
  errorInline: { color: "var(--negative)", fontSize: 12 },
};
