from pathlib import Path
from PIL import Image,ImageDraw
import hashlib,json,datetime
r=Path('/tmp/m3-hatcher')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
books=[{'id':'AT','title':'Algebraic Topology','author':'Allen Hatcher','homepage':'https://pi.math.cornell.edu/~hatcher/','download_page':'https://pi.math.cornell.edu/~hatcher/AT/ATpage.html','pdf_url':'https://pi.math.cornell.edu/~hatcher/AT/AT.pdf','local_pdf':str(r/'AT.pdf'),'physical_page_count':560,'selection_note':'Official page states AT.pdf contains most recent corrections; AT+.pdf is older clickable-TOC version.'}, {'id':'TNbook','title':'Topology of Numbers','author':'Allen Hatcher','homepage':'https://pi.math.cornell.edu/~hatcher/','download_page':'https://pi.math.cornell.edu/~hatcher/TN/TNpage.html','pdf_url':'https://pi.math.cornell.edu/~hatcher/TN/TNbook.pdf','local_pdf':str(r/'TNbook.pdf'),'physical_page_count':362,'selection_note':'Official page identifies TNbook.pdf as minor revision of print edition; TNbookpub.pdf is print version.'}]
for b in books:b['sha256']=sha(Path(b['local_pdf']));b['bytes']=Path(b['local_pdf']).stat().st_size
cases=[
('hatcher-at-genus2-polygon','AT',14,'5',[644,308,785,448], 'Locate only the octagonal edge-identification polygon corresponding to the genus-2 surface. Include its arrow/edge labels; exclude the square, dodecagon, and surface pictures.', 'The middle row pairs a double torus with an octagon; the adjacent text states that an orientable surface of genus g is constructed from a polygon with 4g sides.', [109,151,818,203]),
('hatcher-at-negative-link','AT',31,'22',[634,457,813,562], 'Locate only the linked-circle illustration labeled B_{-3}, including circle A and the B_{-3} label. Exclude B_2 above and the addition diagrams below.', 'The paragraph explains positive or negative linking numbers according to the forward/backward orientation through A; this is the lower member of the two stacked oriented-link examples.', [108,328,612,590]),
('hatcher-at-tree-height','AT',94,'85',[669,1002,807,1158], 'Locate the tree drawn with horizontal height levels that illustrates the function h:X→R. Include the whole tree and its horizontal levels, but exclude surrounding proof text.', 'The last paragraph constructs increasing subtrees Y_n and gives vertices in Y_n minus Y_{n-1} height n.', [108,929,659,1169]),
('hatcher-tn-sphere-projection','TNbook',23,'15',[176,69,750,464], 'Locate the complete sphere-projection figure with the north pole N=(0,0,1), point P=(x,y,z), and point Q=(u,v,0). Include axes and annotation formulas; exclude the derivation below.', 'The paragraph immediately below starts with the vertical plane containing triangle ONQ and relates OQ, OP-prime, r and z.', [109,477,818,606]),
('hatcher-tn-farey-lower','TNbook',30,'22',[118,845,804,1150], 'Locate the lower illustration that connects the circular Farey diagram to the straight-boundary version with dashed projection lines. Include both linked representations and fraction labels; exclude the upper half-plane-only diagram.', 'The paragraph immediately above explains labeling rational points on the circle via corresponding rational points on the x-axis, then filling in triangles by the mediant rule.', [109,678,818,834]),
('hatcher-tn-local-edge','TNbook',99,'91',[649,881,809,963], 'Locate only the small local tree-edge illustration whose four surrounding regions are labeled p,q,r,s. Exclude the large circular topograph above.', 'The adjacent paragraph states that values p,q,r,s around an edge produce the arithmetic progression p, q+r, s.', [108,850,646,978]),
]
rows=[]
for case,book,physical,printed,bbox,request,association,text_box in cases:
 p=r/f'{book}-p{physical}.png';im=Image.open(p).convert('RGB');width,height=im.size
 row={'id':case,'book_id':book,'physical_pdf_page_1based':physical,'printed_page_label':printed,'page_png':str(p),'page_png_sha256':sha(p),'image_width':width,'image_height':height,'request':request,'gold':{'bbox_xyxy_pixels':bbox,'bbox_xyxy_normalized':[bbox[0]/width,bbox[1]/height,bbox[2]/width,bbox[3]/height], 'associated_text_bbox_xyxy_pixels':text_box,'association_reference':association,'annotation_policy':'Manually chosen by Codex visual inspection of the Poppler page PNG before candidate/detector execution; not obtained from PDF vector bounds, OCR or detector output. Include target labels and strokes with small margin, exclude unrelated nearby diagrams/text.'}}
 rows.append(row);draw=ImageDraw.Draw(im);draw.rectangle(bbox,outline='red',width=3);draw.rectangle(text_box,outline='blue',width=2);im.save(r/f'{case}-gold.png')
manifest={'version':'hatcher-real-page-manual-gold-v1','created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'purpose':'Pre-candidate source selection and visual grounding annotations for actual textbook pages','rendering':'pdftoppm -f PHYSICAL -l PHYSICAL -scale-to 1200 -singlefile -png SOURCE OUTPUT; resulting 928x1200 full page. Coordinates top-left origin; x2/y2 are right/bottom bounds.','copyright_scope':'Downloaded from author official pages for authorized private local testing. No redistribution permission inferred. Entire books and page crops remain /tmp, not repo/docs.','annotation_limitations':'Single independent annotating Codex agent using visual inspection, not human expert/dual-annotator consensus. Association descriptions are task references, not measured candidate results.','books':books,'cases':rows}
(r/'manual-gold.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'cases':len(rows),'books':[{k:b[k] for k in ['id','sha256','bytes']} for b in books]},indent=2))
