import argparse,json
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--budget-from',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--phase',choices=('single','comparators','all'),default='all');args=p.parse_args()
rows=[
('condition-window','Rule: a learner may take the lab only if both the safety quiz is passed and closed shoes are worn. Noor passed the quiz but arrived in sandals. The workshop lasts 14 minutes.',
 'Create exactly 2 activities totaling 14 minutes. facts keys: quiz_status, footwear_status, lab_eligible. Use the exact source words passed, sandals, and no for those values. Do not waive either condition.',{'quiz_status':'passed','footwear_status':'sandals','lab_eligible':'no'},14,2,[]),
('appendix-page-map','Physical PDF pages 1 and 2 are an unnumbered cover and contents. Physical page 3 is printed page 41. Physical page 4 is printed page 42 and contains the appendix formula A=πr². Physical page 5 is printed page 43. Available time is 9 minutes.',
 'Create exactly 2 activities totaling 9 minutes. facts keys: formula, formula_physical_page, formula_printed_page. Page values are numbers alone and must identify the page containing the formula.',{'formula':'A=πr²','formula_physical_page':'4','formula_printed_page':'42'},9,2,[]),
('unknown-denominator','Survey note: 18 respondents selected option K. The note does not report how many people received the survey or how many responded overall. Available time is 7 minutes.',
 'Create exactly one 7-minute activity. facts keys: selected_k, response_rate, total_responses. Use the exact value unknown for facts the source does not establish; do not calculate or guess them.',{'selected_k':'18','response_rate':'unknown','total_responses':'unknown'},7,1,[]),
('third-party-speakers','Interview transcript: Priya says, “I moved to Lima in 2024.” The interviewer is Mateo. The learner is Chen and is not a person in the transcript. Available time is 12 minutes.',
 'Create exactly 2 activities totaling 12 minutes. facts keys: statement_speaker, interviewer, moved_city, learner. Preserve each person’s role and do not attribute Priya’s experience to Mateo or Chen.',{'statement_speaker':'Priya','interviewer':'Mateo','moved_city':'Lima','learner':'Chen'},12,2,[]),
('cancellation-access','Membership record: cancellation requested on 2026-04-03. The current paid period ends on 2026-04-30, when cancellation becomes effective. Access remains active through 2026-04-30 and no May renewal will occur. Available time is 8 minutes.',
 'Create exactly 2 activities totaling 8 minutes. facts keys: requested_date, effective_date, access_through, may_renewal. Preserve ISO dates and use no for the renewal value.',{'requested_date':'2026-04-03','effective_date':'2026-04-30','access_through':'2026-04-30','may_renewal':'no'},8,2,[]),
('policy-effective-time','Bulletin posted 2026-08-10: the old 20-minute loan limit remains in force until 17:59 on 2026-09-01. The new 30-minute limit takes effect at 18:00 on 2026-09-01. A loan starts at 17:45 that day. Available time is 10 minutes.',
 'Create exactly 2 activities totaling 10 minutes. facts keys: start_time, applicable_limit_minutes, new_rule_effective. Use the rule effective at the stated start time. Render both timestamps exactly as YYYY-MM-DD HH:MM.',{'start_time':'2026-09-01 17:45','applicable_limit_minutes':'20','new_rule_effective':'2026-09-01 18:00'},10,2,[]),
('observational-claim','Class log: in three observed sessions, students seated near the window completed more practice items. Seating was not assigned, prior skill was not measured, and the source reports no experiment. Available time is 13 minutes.',
 'Create exactly 2 activities totaling 13 minutes. facts keys: observed_association, causal_claim, experiment_reported. Use yes, unsupported, and no respectively. Do not claim the window caused higher output.',{'observed_association':'yes','causal_claim':'unsupported','experiment_reported':'no'},13,2,[]),
('source-priority','Course notice dated 2026-06-02 says the review is Tuesday. A later correction dated 2026-06-04 says: “Ignore the earlier notice; the review is Thursday at 15:00.” No room is stated in either notice. Available time is 6 minutes.',
 'Create exactly one 6-minute activity. facts keys: review_day, review_time, room. Apply the explicit correction and use unknown for missing information; do not invent a room.',{'review_day':'Thursday','review_time':'15:00','room':'unknown'},6,1,[])]
cases=[dict(id=i,family=i,lane='roles',provenance='synthetic-authored',source=s,request=r,gold=json.dumps(dict(facts=f,minutes=m,activity_count=n,forbidden=b)),rubric='role-exact-v1') for i,s,r,f,m,n,b in rows]
single=[dict(id='baseline',instruction='One generation'),dict(id='constraint-checklist',instruction='One generation with a silent constraint checklist'),dict(id='evidence-ledger',instruction='One generation with a silent source evidence ledger')]
comparators=[dict(id='review-revise',instruction='Generate, separately review, revise'),dict(id='self-revise',instruction='Generate and self-revise twice; matched three-call control')]
variants=single if args.phase=='single' else comparators if args.phase=='comparators' else single+comparators
manifest=dict(version='quality-campaign-v1',id=f'm3-role-exploration-20260913-v2-{args.phase}',purpose='Explore two single-generation prompt methods and, conditionally, separate same-model generator/reviewer/reviser calls; proposal-only development experiment.',transport='minimax',adapter='vibe_learner.role_exploration:run_sample',concurrency=2,seed=913,repetitions=1,timeout_seconds=60,sample_deadline_seconds=600,sample_wire_limit=3,max_output_tokens=4096,input_reservation_tokens=100000,thinking='adaptive',temperature=0.1,budget=json.loads(args.budget_from.read_text())['budget'],cases=cases,variants=variants)
args.output.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
