"""Review the deterministic plan prerequisite and real Study confirmation flow."""
import argparse
import json
from pathlib import Path


def review(paths):
    rows = []
    for path in paths:
        for line in path.read_text().splitlines():
            row = json.loads(line)
            before, after = row.get('plan_before') or {}, row.get('plan_after_decisions') or {}
            decisions = row.get('confirmation_decisions') or []
            rejected = row['repetition'] == 1
            if rejected:
                correct = bool(before) and after == before
            elif row['case_id'] == 'plan_title_confirmation':
                correct = after.get('course_title') == '方程求解与代入检验' and after.get('schedule') == before.get('schedule')
            else:
                schedules = after.get('schedule') or []
                correct = len(schedules) == 2 and [s['status'] for s in schedules] == ['completed', 'planned'] and after.get('course_title') == before.get('course_title')
            expected_revision = before.get('revision', 0) + (0 if rejected else 1)
            rows.append({'operation_id': row.get('harness_operation_id'), 'case_id': row['case_id'], 'repetition': row['repetition'],
                'chat_boundary_success': row['boundary_success'], 'unchanged_until_confirmation': row.get('plan_unchanged_before_confirmation'),
                'exactly_one_confirmation': row.get('confirmation_count') == 1,
                'decision_success': len(decisions) == 1 and decisions[0]['http_status'] == 200,
                'duplicate_equal': len(decisions) == 1 and decisions[0]['duplicate_equal'],
                'final_plan_matches_task': correct, 'revision_matches_one_decision': after.get('revision') == expected_revision,
                'reply': ((row.get('receipt') or {}).get('result') or {}).get('reply')})
    return {'scope': 'synthetic plan state plus live Study proposal and confirmation API checks',
        'limitations': ['Plan prerequisite is imported, not generated by M3 in this experiment.',
            'Chat Harness evidence does not imply separately admitted Harness identity for the confirmation endpoint.',
            'Developer-authored state checks do not certify independent model quality or UI delivery.'], 'rows': rows}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--evidence', type=Path, nargs='+', required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(json.dumps(review(args.evidence), ensure_ascii=False, indent=2) + '\n')
