import { test, expect } from "@playwright/test";
const api = process.env.PLAN_REVISION_TEST_API_URL;
test.skip(!api, "Requires disposable mock backend tests.plan_revision_browser_server");
test("independent live revision: accept then rollback keeps newly committed progress", async ({ page, request }, info) => {
  const root = api!;
  await page.addInitScript(root => {
    window.__VIBE_LEARNER_DESKTOP_CONFIG__ = { aiBaseUrl: root, isDesktop: false, platform: "unknown", secretStorageMode: "plain_text", vaultState: "unconfigured", vaultPath: "", storageRoot: "", startupError: "" };
  }, root);
  const requests: {method:string; path:string}[] = [];
  page.on("request", r => { if(r.url().startsWith(root)) requests.push({method:r.method(),path:new URL(r.url()).pathname}); });
  const originalResponse = await request.get(`${root}/learning-plans/plan-cas`);
  expect(originalResponse.ok()).toBe(true);
  const original = await originalResponse.json();
  expect(original.revision).toBe(0);
  await page.goto("/plan");
  await page.getByText("修订计划 · 版本 0", { exact: true }).click();
  const panel = page.getByRole("region", { name: "计划修订", exact: true });
  await panel.getByRole("textbox", { name: "修订要求" }).fill("Add an independent review pass");
  await panel.getByRole("button", { name: "生成修订预览", exact: true }).click();
  await expect(panel.getByRole("table", { name: "修订差异" })).toBeVisible();
  await panel.getByRole("button", { name: "接受修订", exact: true }).click();
  await expect(page.getByText("修订计划 · 版本 1", { exact: true })).toBeVisible();
  const accepted = await (await request.get(`${root}/learning-plans/plan-cas`)).json();
  expect(accepted.overview).toContain("Add an independent review pass");
  const progressResponse = await request.patch(`${root}/learning-plans/plan-cas/progress`, { data: { expected_revision: 1, schedule_ids: [accepted.schedule[0].id], status: "completed", note: "Independent persisted progress" } });
  expect(progressResponse.ok()).toBe(true);
  const progressed = await progressResponse.json();
  expect(progressed.revision).toBe(2);
  await panel.getByRole("button", { name: "刷新当前计划", exact: true }).click();
  await expect(page.getByText("修订计划 · 版本 2", { exact: true })).toBeVisible();
  await panel.getByRole("combobox", { name: "历史版本" }).selectOption("0");
  await panel.getByRole("button", { name: "预览回滚", exact: true }).click();
  await expect(panel.getByRole("button", { name: "接受修订", exact: true })).toBeVisible();
  await panel.getByRole("button", { name: "接受修订", exact: true }).click();
  await expect(page.getByText("修订计划 · 版本 3", { exact: true })).toBeVisible();
  const rolledBack = await (await request.get(`${root}/learning-plans/plan-cas`)).json();
  expect(rolledBack.overview).toBe(original.overview);
  expect(rolledBack.schedule).toEqual(progressed.schedule);
  expect(rolledBack.progress_events).toEqual(progressed.progress_events);
  expect(rolledBack.progress_summary).toEqual(progressed.progress_summary);
  expect(rolledBack.study_unit_progress).toEqual(progressed.study_unit_progress);
  expect(rolledBack.study_units).toEqual(original.study_units);
  await info.attach("live-revision-evidence.json", { body: JSON.stringify({ requests, original, accepted, progressed, rolledBack }), contentType: "application/json" });
});
